### ISSUE TITLE
Think of what data we need

### ISSUE THREAD

**Issue by AVishal9** [UniLuFS2020-ReplicationSeminar/CE2_Alluri_Hess_Lengwiler_#2]
The 'get' request has resulted in accessing 'metadata' of articles.
Run the code, look through the output and think of what metadata we should save, ie; what would be useful?

API Documentation for reference: https://open-platform.theguardian.com/documentation/search

**Comment by silvanhess** [comment]
that documentation really helped in refining the query so we get more specific articles on travel restricitons during covid-19
